import type { Metadata } from "next";
import ErrorWrapper from "./error-wrapper";
import { ThemeProvider } from "./components/theme-provider";

export const metadata: Metadata = {
  title: {
    default: "Create Next App",
    template: "%s | Next App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={`antialiased`}>
          {/* <ErrorWrapper>{children}</ErrorWrapper> */}
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
